[project]
name = "tokopaedi-review-scrapper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bs4>=0.0.2",
    "pandas>=2.3.2",
    "pyyaml>=6.0.2",
    "rich>=14.1.0",
    "selenium>=4.35.0",
]
